# Generated by Django 5.0.3 on 2024-04-30 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lionapp', '0003_member_alter_comment_post_id_alter_post_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
    ]
