# Generated by Django 5.0.3 on 2024-04-30 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lionapp', '0004_rename_post_id_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
